name: build-and-publish

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 1 * *'  # 03:00 UTC on the 1st of every month

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build and push multi-arch image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          YEAR=$(date -u +%Y)
          MONTH=$(date -u +%m)
          DATE_TAG=v${YEAR}.${MONTH}
          SHORT_SHA=${GITHUB_SHA::7}
          echo "date_tag=${DATE_TAG}" >> $GITHUB_OUTPUT
          echo "short_sha=sha-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Extract metadata (labels)
        id: ghmeta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.meta.outputs.date_tag }}
            type=raw,value=${{ steps.meta.outputs.short_sha }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          sbom: false
          tags: ${{ steps.ghmeta.outputs.tags }}
          labels: ${{ steps.ghmeta.outputs.labels }}
